version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: theksqu4r3gr0upMx
      MYSQL_DATABASE: cfo_reporting
      MYSQL_USER: jenkins_user
      MYSQL_PASSWORD: theksqu4r3gr0upMx
    ports:
      - "32267:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  springboot-app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cfo_reporting
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
