version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      
      MYSQL_ROOT_PASSWORD: theksqu4r3gr0upMx
      MYSQL_DATABASE: cfo_reporting
      MYSQL_USER: jenkins_user
      MYSQL_PASSWORD: theksqu4r3gr0upMx

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cfo_reporting
 
volumes:
  mysql-data: